site_name: Biopet user manual
pages:
- ['index.md', 'Home']
- ['config.md', 'Config']
- ['pipelines/basty.md', 'pipelines', 'Basty']
- ['pipelines/GATK-pipeline.md', 'pipelines', 'GATK-pipeline']
- ['pipelines/flexiprep.md', 'pipelines', 'Flexiprep']
- ['pipelines/gentrap.md', 'pipelines', 'Gentrap']
- ['pipelines/mapping.md', 'pipelines', 'Mapping']
- ['pipelines/sage.md', 'pipelines', 'Sage']
- ['pipelines/yamsvp.md', 'pipelines', 'Yamsvp']
- ['tools/SamplesTsvToJson.md','tools','SamplesTsvToJson']
- ['tools/BastyGenerateFasta.md','tools','BastyGenerateFasta']
- ['cluster/oge.md', 'OpenGridEngine']
- ['about.md', 'About']
- ['license.md', 'License']
theme: readthedocs
repo_url: https://git.lumc.nl/biopet/biopet
