site_name: Biopet user manual
pages:
- ['index.md', 'Home']
- ['config.md', 'Config']
- ['pipelines/basty.md', 'Pipelines', 'Basty']
- ['pipelines/GATK-pipeline.md', 'Pipelines', 'GATK-pipeline']
- ['pipelines/flexiprep.md', 'Pipelines', 'Flexiprep']
- ['pipelines/mapping.md', 'Pipelines', 'Mapping']
- ['pipelines/sage.md', 'Pipelines', 'Sage']
- ['tools/SamplesTsvToJson.md','tools','SamplesTsvToJson']
- ['tools/BastyGenerateFasta.md','tools','BastyGenerateFasta']
- ['tools/bedtointerval.md','tools','BedToInterval']
- ['tools/bedtoolscoveragetocounts.md','tools','BedtoolsCoverageToCounts']
- ['tools/BiopetFlagstat.md','tools','BiopetFlagstat']
- ['tools/CheckAllelesVcfInBam.md','tools','CheckAllelesVcfInBam']
- ['tools/ExtractAlignedFastq.md','tools','ExtractAlignedFastq']
- ['tools/FastqSplitter.md', 'tools','FastqSplitter']
- ['tools/FindRepeatsPacBio.md','tools','FindRepeatsPacBio']
- ['tools/VcfFilter.md','tools','VcfFilter']
- ['tools/MpileupToVcf.md', 'tools', 'MpileupToVcf']
- ['tools/sagetools.md', 'tools', 'Sagetools']
- ['tools/WipeReads.md', 'tools', 'WipeReads']
- ['cluster/oge.md', 'OpenGridEngine']
- ['about.md', 'About']
- ['license.md', 'License']
theme: readthedocs
repo_url: https://git.lumc.nl/biopet/biopet