site_name: Biopet User Manual
pages:
- Home: 'index.md'
- General:
    - Config: 'general/config.md'
    - Requirements: 'general/requirements.md'
- Pipelines:
    - Basty: 'pipelines/basty.md'
    - Bam2Wig: 'pipelines/bam2wig.md'
    - Carp: 'pipelines/carp.md'
    - Gentrap: 'pipelines/gentrap.md'
    - Shiva: 'pipelines/shiva.md'
    - Flexiprep: 'pipelines/flexiprep.md'
    - Mapping: 'pipelines/mapping.md'
    - Toucan: 'pipelines/toucan.md'
    - Sage: 'pipelines/sage.md'
- Tools:
    - SamplesTsvToJson: 'tools/SamplesTsvToJson.md'
    - BastyGenerateFasta: 'tools/bedtointerval.md'
    - BedToInterval: 'tools/bedtointerval.md'
    - BedtoolsCoverageToCounts: 'tools/bedtoolscoveragetocounts.md'
    - BiopetFlagstat: 'tools/BiopetFlagstat.md'
    - CheckAllelesVcfInBam: 'tools/CheckAllelesVcfInBam.md'
    - ExtractAlignedFastq: 'tools/ExtractAlignedFastq.md'
    - FastqSplitter: 'tools/FastqSplitter.md'
    - FindRepeatsPacBio: 'tools/FindRepeatsPacBio.md'
    - VcfFilter: 'tools/VcfFilter.md'
    - MpileupToVcf: 'tools/MpileupToVcf.md'
    - Sagetools: 'tools/sagetools.md'
    - VepNormalizer: 'tools/VepNormalizer.md'
    - WipeReads: 'tools/WipeReads.md'
    - BastyGenerateFasta: 'tools/BastyGenerateFasta.md'
- Release notes:
    - 0.4.0: 'release_notes_0.4.0.md'
    - 0.3.2: 'release_notes_0.3.2.md'
    - 0.3.1: 'release_notes_0.3.1.md'
    - 0.3.0: 'release_notes_0.3.0.md'
- About: 'about.md'
- License: 'license.md'
#- ['developing/Setup.md', 'Developing', 'Setting up your local development environment']
#theme: readthedocs
repo_url: https://git.lumc.nl/biopet/biopet
