
configfile: "autodoc-tools.yml"
biopet_dir = config['biopet_dir']
tools_dir = config['tools_dir']}"
docs_dir =  config['docs_dir']}"

#rule all:
#  input: 
#    "{biopet_dir}/{docs_dir}/{tool}.md"


rule create_temp_docs:
  input:
    expand("{dir}/*.scala", dir= tools_dir)
  output:
    "tool_list.txt"
  shell:
    "echo '' > output ; "
    "for file in {input} ; "
    "do ;"
    "file_no_path=${file##*/}; "
    "file_no_extension=${file_no_path%.scala}; "
    "destfile={docs_dir}/${file_no_extension.md}; "
    "if [ ! -f $destfile ]; "
    "then ; "
    "echo $destfile >> {output} ; "
    "fi" 
    "done"

